[package]
name = "cycles-ledger-client"
version = "0.1.1-alpha.1"
edition = "2021"

[dependencies]
candid = { workspace = true }
ic-cdk = { workspace = true }
serde = { workspace = true }
serde_bytes = { workspace = true }
