[didc.rust]
target = "custom"
template = "scripts/bind/pic/cycles_depositor.hbs"
# any tags mentioned from hbs
candid_crate = "candid"
canister_name = "CyclesDepositor"

[rust]
visibility = "pub(crate)"
attributes = "#[derive(CandidType, Deserialize, Debug)]"
