[didc.rust]
target = "custom"
template = "scripts/bind/pic/template.hbs"
# any tags mentioned from hbs
candid_crate = "candid"
canister_name = "signer"

[rust]
visibility = "pub(crate)"
attributes = "#[derive(CandidType, Deserialize, Debug, Eq, PartialEq, Clone)]"