name: 'Checks that the bindings are up to date'
description: |
  Formats all the code in the repository
runs:
  using: "composite"
  steps:
    - name: Install tools
      shell: bash
      run: |
        scripts/setup didc
    - name: Generate bindings
      shell: bash
      run: |
        scripts/bind.sh
    - name: Format code
      shell: bash
      uses: ./.github/actions/format
    - name: Check for changes
      shell: bash
      run: |
        test -z "$(git status --porcelain src)" || {
                echo "FIX: Please update the canister bindings."
                git diff
                exit 1
        }
