# Configuration for cargo audit.
#
# For examples, see: https://github.com/rustsec/rustsec/blob/main/cargo-audit/audit.toml.example

[advisories]
ignore=[
  # Key recovery is not possible as this code performs no signing itself; signing is done as a threshold signature by the underlying replicas.
  # We can therefore ignore timing attack advisories.
  "RUSTSEC-2024-0344",
  "RUSTSEC-2023-0071",
  # To quote: serde-cbor is old but continues to be correct and the best available for our purposes.
  # Note: ciborium is the shiny new alternative but it is not a drop in replacement for serde-cbor.
  "RUSTSEC-2021-0127",
]
