#!/usr/bin/env bash
: The commit and any semantic version tags to be stored in the canister metadata.

# The $ in the single quotes is intentional; it matches the end of the file.
# shellcheck disable=SC2016
git rev-parse HEAD >target/commit
git tag -l --contains HEAD >target/tags
