#!/usr/bin/env bash
# Note:
# * `sha256sum` prints the hash of each file;
# * The `wc -c` in the awk code gets the size in bytes of each file;
# * The AWK code also adds a header and footer;
# * `column -t` formats the data as a table;
# * `tee` saves a copy of the printout in a file; that file will be included in releases.
find out/ -type f -print0 | grep -vz filelist.txt | xargs --null sha256sum | tee out/filelist.txt
