#!/usr/bin/env bash
set -euo pipefail
SOURCE_DIR="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"
PATH="$SOURCE_DIR:$PATH"

print_help() {
  cat <<-EOF
	Gets released assets from CI, for use in a proposal.

	# Prerequisites
	- The desired release has been created and published.
	EOF
}

# Source the clap.bash file ---------------------------------------------------
source "$SOURCE_DIR/clap.bash"
# Define options
clap.define short=n long=network desc="The dfx network to use" variable=DFX_NETWORK default="ic"
clap.define short=t long=tag desc="The release candidate tag" variable=RELEASE_CANDIDATE_TAG
# Source the output file ----------------------------------------------------------
source "$(clap.build)"
cd "$SOURCE_DIR/.."
export DFX_NETWORK

ASSET_DIR=release/ci
rm -fr "${ASSET_DIR}"
mkdir -p "${ASSET_DIR}"
cd "${ASSET_DIR}"
gh release download "$RELEASE_CANDIDATE_TAG"
echo "Assets in $ASSET_DIR:"
sha256sum ./*
