#!/usr/bin/env bash
set -euxo pipefail

print_help() {
  cat <<-EOF
	Pushes a git tag.  GitHub actions will create a release for this tag.
	EOF
}

version="$(cargo metadata --format-version 1 | jq -r '.packages[] | select(.name == "signer") | .version')"
tag="v$version"
git tag "$tag"
git push origin "refs/tags/$tag"
echo "Waiting for GitHub release action..."
sleep 5
gh run watch "$(gh run list --workflow Release --branch "$tag" --json databaseId -q '.[0].databaseId')"
